### ISSUE TITLE
执行self._prune_and_build_new_modelV2()之后，new_model的通道数与原始模型不同

### ISSUE THREAD

**Issue by sunyclj** [Zj-BinXia/SSL#11]
_prune_and_build_new_modelV2中new_layer根据kept_filter, kept_chl设置，不会包括所有的层，在模型更新时，得到的new_model也就只包含这些层，通道数就与原始模型不对应，在测试时候报错，请问是什么原因呢？

**Comment by Zj-BinXia** [comment]
你是readme的方法进行测试的吗

**Comment by sunyclj** [comment]
> 你是readme的方法进行测试的吗

不是，SSL-master/basicsr/pruner/SSL_pruner.py中def optimize_parameters(self, current_iter)，`#if self.prune_state in [
        #    "stabilize_reg"] and self.total_iter - self.iter_stabilize_reg == self.args.stabilize_reg_interval:   #self.args.stabilize_reg_interval=14000
        while True: 
            self.logger.info(
                f"==> 'stabilize_reg' is done. Iter {self.total_iter}.About to prune and build new model. Testing...")
            self.val()

            # if self.args.greg_mode in ['all']:
            self._get_kept_wg_L1()
            self.logger.info(f'==> Get pruned_wg/kept_wg.')

            self._merge_wn_scale_to_weightsV2()
            self._prune_and_build_new_modelV2()
            path = self._save_model('model_prune_optimization.pt')
            self.logger.info(f"==> Pruned and built a new model. Ckpt saved: '{path}'. Testing...")
            self.val()`
我想确认在自定义的模型上通过您的剪枝方法提升的效率情况，所以把循环终止条件注释掉，换成了while True；这里的第二个self.val()报错通道不对，我打印出new model每层的尺寸，确实与原始模型不同了

**Comment by sunyclj** [comment]
> > 你是readme的方法进行测试的吗
> 
> 不是，SSL-master/basicsr/pruner/SSL_pruner.py中def optimize_parameters(self, current_iter)，`#if self.prune_state in [ # "stabilize_reg"] and self.total_iter - self.iter_stabilize_reg == self.args.stabilize_reg_interval: #self.args.stabilize_reg_interval=14000 while True: self.logger.info( f"==> 'stabilize_reg' is done. Iter {self.total_iter}.About to prune and build new model. Testing...") self.val()
> 
> ```
>         # if self.args.greg_mode in ['all']:
>         self._get_kept_wg_L1()
>         self.logger.info(f'==> Get pruned_wg/kept_wg.')
> 
>         self._merge_wn_scale_to_weightsV2()
>         self._prune_and_build_new_modelV2()
>         path = self._save_model('model_prune_optimization.pt')
>         self.logger.info(f"==> Pruned and built a new model. Ckpt saved: '{path}'. Testing...")
>         self.val()`
> ```
> 
> 我想确认在自定义的模型上通过您的剪枝方法提升的效率情况，所以把循环终止条件注释掉，换成了while True；这里的第二个self.val()报错通道不对，我打印出new model每层的尺寸，确实与原始模型不同了

**Comment by sunyclj** [comment]
> 你是readme的方法进行测试的吗
model_prune_optimization.pt保存之后，进入到self.val()-->self.test(),
`with torch.no_grad():
            flag = True
            self.output = self.model(self.lq,flag)`
我的模型其他层都不进行剪枝头，只有模型的主体部分参与剪枝，也就是basicvsr单向特征传播的方式，结构如下

ConvResidualBlocks(
  (main): Sequential(
    (0): Conv2d(67, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Sequential(
      (0): ResidualBlockNoBN_WN(
        (conv1): Conv2d(15, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(30, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (1): ResidualBlockNoBN_WN(
        (conv1): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(31, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (2): ResidualBlockNoBN_WN(
        (conv1): Conv2d(29, 29, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(29, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (3): ResidualBlockNoBN_WN(
        (conv1): Conv2d(38, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(30, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (4): ResidualBlockNoBN_WN(
        (conv1): Conv2d(32, 23, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(23, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (5): ResidualBlockNoBN_WN(
        (conv1): Conv2d(31, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (6): ResidualBlockNoBN_WN(
        (conv1): Conv2d(32, 28, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(28, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (7): ResidualBlockNoBN_WN(
        (conv1): Conv2d(33, 29, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(29, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (8): ResidualBlockNoBN_WN(
        (conv1): Conv2d(27, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(24, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (9): ResidualBlockNoBN_WN(
        (conv1): Conv2d(37, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(24, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (10): ResidualBlockNoBN_WN(
        (conv1): Conv2d(40, 34, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(34, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (11): ResidualBlockNoBN_WN(
        (conv1): Conv2d(34, 27, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(27, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (12): ResidualBlockNoBN_WN(
        (conv1): Conv2d(32, 34, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(34, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (13): ResidualBlockNoBN_WN(
        (conv1): Conv2d(29, 35, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(35, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (14): ResidualBlockNoBN_WN(
        (conv1): Conv2d(23, 21, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(21, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (15): ResidualBlockNoBN_WN(
        (conv1): Conv2d(29, 20, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(20, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (16): ResidualBlockNoBN_WN(
        (conv1): Conv2d(41, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(24, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (17): ResidualBlockNoBN_WN(
        (conv1): Conv2d(32, 26, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(26, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (18): ResidualBlockNoBN_WN(
        (conv1): Conv2d(33, 25, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(25, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (19): ResidualBlockNoBN_WN(
        (conv1): Conv2d(29, 27, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(27, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (20): ResidualBlockNoBN_WN(
        (conv1): Conv2d(34, 23, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(23, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (21): ResidualBlockNoBN_WN(
        (conv1): Conv2d(35, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(31, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (22): ResidualBlockNoBN_WN(
        (conv1): Conv2d(33, 30, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(30, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (23): ResidualBlockNoBN_WN(
        (conv1): Conv2d(37, 28, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(28, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (24): ResidualBlockNoBN_WN(
        (conv1): Conv2d(34, 23, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(23, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (25): ResidualBlockNoBN_WN(
        (conv1): Conv2d(30, 22, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(22, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (26): ResidualBlockNoBN_WN(
        (conv1): Conv2d(31, 25, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(25, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
      (27): ResidualBlockNoBN_WN(
        (conv1): Conv2d(29, 33, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (conv2): Conv2D_WN(33, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (relu): ReLU(inplace=True)
      )
    )
  )
)
测试时运行到这里就提示通道不匹配错误
RuntimeError: Given groups=1, weight of size [30, 15, 3, 3], expected input[1, 64, 180, 320] to have 15 channels, but got 64 channels instead
我运行您源代码，这里测试时候的模型的通道数也是与原始模型不同，测试流程可以走通；我这个是什么原因，您这边根据我提供的信息可以分析出吗？
