### ISSUE TITLE
REDS data problem

### ISSUE THREAD

**Issue by zxd-cqu** [Zj-BinXia/SSL#3]
Why does the file(**SSL-master/basicsr/data/meta_info/meta_info_REDS_GT.txt**) include folders with numbers greater than 269? Isn't REDS supposed to have 240+30 folders?
......
267 100 (720,1280,3)
268 100 (720,1280,3)
269 100 (720,1280,3)
270 100 (720,1280,3)
271 100 (720,1280,3)
272 100 (720,1280,3)
273 100 (720,1280,3)

**Comment by Zj-BinXia** [comment]
We follow the basicsr. Please see basicsr.data.reds_dataset.py, REDSRecurrentDataset will remove 4 clips for validation. So the training REDS is actually 270 clips.
